=== cvale21/DAW2020/T3/project_record.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project_record (title, metadata, workteam, abstract, deliverables, date)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT metadata (key_name, project_title, subtitle?, begin_date, end_date, supervisors)>

<!ELEMENT key_name (#PCDATA) >
<!ELEMENT project_title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) > 
<!ELEMENT begin_date (#PCDATA) > 
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisors (supervisor+) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor href CDATA #REQUIRED >


<!-- WORKTEAM -->

<!ELEMENT workteam (member, member?, member?) >

<!ELEMENT member (num_aluno, nome, email, ref?) >
<!ELEMENT num_aluno (#PCDATA) >
<!ATTLIST num_aluno id ID #REQUIRED >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT ref (#PCDATA) >
<!ATTLIST ref url CDATA #IMPLIED >

<!-- Abstract -->

<!ELEMENT abstract (parag)+ >

<!ELEMENT parag (#PCDATA |italic|bold|underlined|link)* >
<!ELEMENT italic (#PCDATA |bold|underlined|link)* >
<!ELEMENT bold (#PCDATA |italic|underlined|link)* >
<!ELEMENT underlined (#PCDATA |bold|italic|link)* >
<!ELEMENT link (#PCDATA |bold|italic|underlined)* >
<!ATTLIST link url CDATA #REQUIRED>

<!-- Deliverables -->

<!ELEMENT deliverables (deliverable)+ >

<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable url CDATA #REQUIRED >

<!-- Date -->
<!ELEMENT date (#PCDATA) >

=== cvale21/DAW2020/T3/project_record.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE project_record SYSTEM "project_record.dtd">

<project_record>
    
    <title>Project Record</title>
    
    <metadata>
        <key_name>Trabalho 3</key_name>
        <project_title>Criar uma Stylesheet XSLT para gerar um Website.</project_title>
        <begin_date>28/10/2020</begin_date>
        <end_date>4/11/2020</end_date>
        <supervisors>
            <supervisor href="http://www.di.uminho.pt/~jcr">Prof. José Carlos Ramalho</supervisor>
        </supervisors>
    </metadata>
    
    <workteam>
        <member>
            <num_aluno id="PG42816"></num_aluno>
            <nome>Cândido Vale</nome>
            <email>pg42816@alunos.uminho.pt</email>
            <ref url="https://github.com/cvale21"></ref>
        </member>
    </workteam>
    
    <abstract>
        <parag> 
            Este trabalho é referente ao <bold>TPC3</bold>, onde o <underlined>objetivo é criar uma stylesheet <italic>XSLT</italic> 
                que permita gerar um Website para o dataset dos <bold>Arqueossítios do NW Português</bold>. </underlined>
        </parag>
        
        <parag>Link para o respositório: 
            <bold><link url="https://github.com/cvale21/DAW2020"></link></bold>
        </parag>
        
    </abstract>
    
    <deliverables>
        <deliverable url="arq.xsl"></deliverable>
        <deliverable url="arq.dtd"></deliverable>
        <deliverable url="project_record.dtd"></deliverable>
        <deliverable url="project_record.xml"></deliverable>
    </deliverables>
    
    <date>4/11/202</date>
    
</project_record>

=== cvale21/DAW2020/T2/project_record.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE project_record SYSTEM "project_record.dtd">

<project_record>
    
    <title>Project Record (Example)</title>
    
    <metadata>
        <key_name>Trabalho 2</key_name>
        <project_title>Especificar um DTD para memórias descritivas</project_title>
        <begin_date>21/10/2020</begin_date>
        <end_date>28/10/2020</end_date>
        <supervisors>
            <supervisor href="http://www.di.uminho.pt/~jcr">Prof. José Carlos Ramalho</supervisor>
        </supervisors>
    </metadata>
    
    <workteam>
        <member>
            <num_aluno id="PG42816"></num_aluno>
            <nome>Cândido Vale</nome>
            <email>pg42816@alunos.uminho.pt</email>
            <ref url="https://github.com/cvale21"></ref>
        </member>
    </workteam>
    
    <abstract>
        <parag> 
            Este trabalho é referente ao <bold>TPC2</bold>, onde o <underlined>objetivo é especificar um <italic>DTD</italic> 
            para memórias descritivas, criando um ficheiro <italic>XML</italic>  que faça uso do <italic>DTD</italic>  especificado.</underlined>
        </parag>
        
        <parag>Link para o respositório: 
            <bold><link url="https://github.com/cvale21/DAW2020"></link></bold>
        </parag>
        
    </abstract>
    
    <deliverables>
        <deliverable url="project_record.dtd"></deliverable>
    </deliverables>
    
    <date>28/10/202</date>
    
</project_record>
